on:
  push:
    branches:
      - main

name: Build and release applications
jobs:
  build:
    name: Build applications
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x.x
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Install fyne cross builder
        run: go get github.com/fyne-io/fyne-cross
      - name: Install test dependencies
        run: sudo apt install -y gcc libgl1-mesa-dev xorg-dev
      - name: Run tests
        run: go test ./...
      - name: Build for Windows
        run: fyne-cross windows -arch=amd64 -output keep_smallest.exe
      - name: Build for Linux
        run: fyne-cross linux -arch=amd64 -output keep_smallest
      - name: Release applications
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "fyne-cross/dist/windows-amd64/keep_smallest.exe.zip, fyne-cross/dist/linux-amd64/keep_smallest.tar.gz"
